/**
 * Country name → ISO 3166-1 alpha-2 code mapping.
 * Used to derive countryCode from LiteAPI's formattedAddress field,
 * which returns country names (e.g., "South Korea") instead of codes.
 */
export const COUNTRY_NAME_TO_CODE: Record<string, string> = {
    // Asia-Pacific
    'philippines': 'PH',
    'south korea': 'KR',
    'korea': 'KR',
    'japan': 'JP',
    'china': 'CN',
    'taiwan': 'TW',
    'hong kong': 'HK',
    'macau': 'MO',
    'thailand': 'TH',
    'vietnam': 'VN',
    'indonesia': 'ID',
    'malaysia': 'MY',
    'singapore': 'SG',
    'cambodia': 'KH',
    'myanmar': 'MM',
    'laos': 'LA',
    'brunei': 'BN',
    'india': 'IN',
    'sri lanka': 'LK',
    'nepal': 'NP',
    'bangladesh': 'BD',
    'pakistan': 'PK',
    'maldives': 'MV',
    'australia': 'AU',
    'new zealand': 'NZ',
    'fiji': 'FJ',

    // Middle East
    'united arab emirates': 'AE',
    'uae': 'AE',
    'saudi arabia': 'SA',
    'qatar': 'QA',
    'bahrain': 'BH',
    'oman': 'OM',
    'kuwait': 'KW',
    'jordan': 'JO',
    'israel': 'IL',
    'turkey': 'TR',
    'türkiye': 'TR',
    'lebanon': 'LB',
    'egypt': 'EG',

    // Europe
    'united kingdom': 'GB',
    'uk': 'GB',
    'england': 'GB',
    'scotland': 'GB',
    'wales': 'GB',
    'france': 'FR',
    'germany': 'DE',
    'italy': 'IT',
    'spain': 'ES',
    'portugal': 'PT',
    'netherlands': 'NL',
    'belgium': 'BE',
    'switzerland': 'CH',
    'austria': 'AT',
    'czech republic': 'CZ',
    'czechia': 'CZ',
    'poland': 'PL',
    'hungary': 'HU',
    'greece': 'GR',
    'croatia': 'HR',
    'sweden': 'SE',
    'norway': 'NO',
    'denmark': 'DK',
    'finland': 'FI',
    'ireland': 'IE',
    'iceland': 'IS',
    'romania': 'RO',
    'bulgaria': 'BG',
    'serbia': 'SR',
    'montenegro': 'ME',
    'slovenia': 'SI',
    'slovakia': 'SK',
    'luxembourg': 'LU',
    'malta': 'MT',
    'cyprus': 'CY',
    'estonia': 'EE',
    'latvia': 'LV',
    'lithuania': 'LT',
    'russia': 'RU',
    'ukraine': 'UA',
    'georgia': 'GE',

    // Americas
    'united states': 'US',
    'usa': 'US',
    'canada': 'CA',
    'mexico': 'MX',
    'brazil': 'BR',
    'argentina': 'AR',
    'chile': 'CL',
    'colombia': 'CO',
    'peru': 'PE',
    'costa rica': 'CR',
    'panama': 'PA',
    'cuba': 'CU',
    'dominican republic': 'DO',
    'jamaica': 'JM',
    'puerto rico': 'PR',
    'bahamas': 'BS',
    'trinidad and tobago': 'TT',
    'ecuador': 'EC',
    'uruguay': 'UY',
    'venezuela': 'VE',
    'bolivia': 'BO',
    'paraguay': 'PY',
    'guatemala': 'GT',
    'honduras': 'HN',
    'el salvador': 'SV',
    'nicaragua': 'NI',
    'belize': 'BZ',

    // Africa
    'south africa': 'ZA',
    'morocco': 'MA',
    'tunisia': 'TN',
    'kenya': 'KE',
    'tanzania': 'TZ',
    'nigeria': 'NG',
    'ghana': 'GH',
    'ethiopia': 'ET',
    'mozambique': 'MZ',
    'mauritius': 'MU',
    'seychelles': 'SC',
    'madagascar': 'MG',
    'senegal': 'SN',
    'rwanda': 'RW',
    'uganda': 'UG',
    'namibia': 'NA',
    'botswana': 'BW',
    'zimbabwe': 'ZW',
    'algeria': 'DZ',
};

/**
 * Country ISO code → most popular tourist city for hotel searches.
 * Used as a fallback when a user searches by country rather than city.
 */
export const COUNTRY_DEFAULT_CITY: Record<string, string> = {
    'PH': 'Manila',
    'KR': 'Seoul',
    'JP': 'Tokyo',
    'CN': 'Beijing',
    'TW': 'Taipei',
    'HK': 'Hong Kong',
    'MO': 'Macau',
    'TH': 'Bangkok',
    'VN': 'Hanoi',
    'ID': 'Bali',
    'MY': 'Kuala Lumpur',
    'SG': 'Singapore',
    'KH': 'Phnom Penh',
    'MM': 'Yangon',
    'LA': 'Luang Prabang',
    'BN': 'Bandar Seri Begawan',
    'IN': 'New Delhi',
    'LK': 'Colombo',
    'NP': 'Kathmandu',
    'BD': 'Dhaka',
    'PK': 'Islamabad',
    'MV': 'Male',
    'AU': 'Sydney',
    'NZ': 'Auckland',
    'FJ': 'Suva',
    'AE': 'Dubai',
    'SA': 'Riyadh',
    'QA': 'Doha',
    'BH': 'Manama',
    'OM': 'Muscat',
    'KW': 'Kuwait City',
    'JO': 'Amman',
    'IL': 'Tel Aviv',
    'TR': 'Istanbul',
    'LB': 'Beirut',
    'EG': 'Cairo',
    'GB': 'London',
    'FR': 'Paris',
    'DE': 'Berlin',
    'IT': 'Rome',
    'ES': 'Madrid',
    'PT': 'Lisbon',
    'NL': 'Amsterdam',
    'BE': 'Brussels',
    'CH': 'Zurich',
    'AT': 'Vienna',
    'CZ': 'Prague',
    'PL': 'Warsaw',
    'HU': 'Budapest',
    'GR': 'Athens',
    'HR': 'Dubrovnik',
    'SE': 'Stockholm',
    'NO': 'Oslo',
    'DK': 'Copenhagen',
    'FI': 'Helsinki',
    'IE': 'Dublin',
    'IS': 'Reykjavik',
    'RO': 'Bucharest',
    'BG': 'Sofia',
    'SR': 'Belgrade',
    'ME': 'Kotor',
    'SI': 'Ljubljana',
    'SK': 'Bratislava',
    'LU': 'Luxembourg City',
    'MT': 'Valletta',
    'CY': 'Nicosia',
    'EE': 'Tallinn',
    'LV': 'Riga',
    'LT': 'Vilnius',
    'RU': 'Moscow',
    'UA': 'Kyiv',
    'GE': 'Tbilisi',
    'US': 'New York',
    'CA': 'Toronto',
    'MX': 'Cancun',
    'BR': 'Rio de Janeiro',
    'AR': 'Buenos Aires',
    'CL': 'Santiago',
    'CO': 'Cartagena',
    'PE': 'Lima',
    'CR': 'San Jose',
    'PA': 'Panama City',
    'CU': 'Havana',
    'DO': 'Punta Cana',
    'JM': 'Kingston',
    'BS': 'Nassau',
    'EC': 'Quito',
    'UY': 'Montevideo',
    'BO': 'La Paz',
    'GT': 'Antigua',
    'HN': 'Tegucigalpa',
    'BZ': 'Belize City',
    'ZA': 'Cape Town',
    'MA': 'Marrakech',
    'TN': 'Tunis',
    'KE': 'Nairobi',
    'TZ': 'Zanzibar',
    'NG': 'Lagos',
    'GH': 'Accra',
    'ET': 'Addis Ababa',
    'MU': 'Port Louis',
    'SC': 'Victoria',
    'RW': 'Kigali',
    'NA': 'Windhoek',
};

/**
 * Canonical country list for autocomplete search.
 * Each entry has a display name and ISO 3166-1 alpha-2 code.
 */
export const COUNTRY_SEARCH_LIST: { name: string; code: string }[] = [
    { name: 'Philippines', code: 'PH' },
    { name: 'South Korea', code: 'KR' },
    { name: 'Japan', code: 'JP' },
    { name: 'China', code: 'CN' },
    { name: 'Taiwan', code: 'TW' },
    { name: 'Hong Kong', code: 'HK' },
    { name: 'Macau', code: 'MO' },
    { name: 'Thailand', code: 'TH' },
    { name: 'Vietnam', code: 'VN' },
    { name: 'Indonesia', code: 'ID' },
    { name: 'Malaysia', code: 'MY' },
    { name: 'Singapore', code: 'SG' },
    { name: 'Cambodia', code: 'KH' },
    { name: 'Myanmar', code: 'MM' },
    { name: 'Laos', code: 'LA' },
    { name: 'Brunei', code: 'BN' },
    { name: 'India', code: 'IN' },
    { name: 'Sri Lanka', code: 'LK' },
    { name: 'Nepal', code: 'NP' },
    { name: 'Bangladesh', code: 'BD' },
    { name: 'Pakistan', code: 'PK' },
    { name: 'Maldives', code: 'MV' },
    { name: 'Australia', code: 'AU' },
    { name: 'New Zealand', code: 'NZ' },
    { name: 'Fiji', code: 'FJ' },
    { name: 'United Arab Emirates', code: 'AE' },
    { name: 'Saudi Arabia', code: 'SA' },
    { name: 'Qatar', code: 'QA' },
    { name: 'Bahrain', code: 'BH' },
    { name: 'Oman', code: 'OM' },
    { name: 'Kuwait', code: 'KW' },
    { name: 'Jordan', code: 'JO' },
    { name: 'Israel', code: 'IL' },
    { name: 'Turkey', code: 'TR' },
    { name: 'Lebanon', code: 'LB' },
    { name: 'Egypt', code: 'EG' },
    { name: 'United Kingdom', code: 'GB' },
    { name: 'France', code: 'FR' },
    { name: 'Germany', code: 'DE' },
    { name: 'Italy', code: 'IT' },
    { name: 'Spain', code: 'ES' },
    { name: 'Portugal', code: 'PT' },
    { name: 'Netherlands', code: 'NL' },
    { name: 'Belgium', code: 'BE' },
    { name: 'Switzerland', code: 'CH' },
    { name: 'Austria', code: 'AT' },
    { name: 'Czech Republic', code: 'CZ' },
    { name: 'Poland', code: 'PL' },
    { name: 'Hungary', code: 'HU' },
    { name: 'Greece', code: 'GR' },
    { name: 'Croatia', code: 'HR' },
    { name: 'Sweden', code: 'SE' },
    { name: 'Norway', code: 'NO' },
    { name: 'Denmark', code: 'DK' },
    { name: 'Finland', code: 'FI' },
    { name: 'Ireland', code: 'IE' },
    { name: 'Iceland', code: 'IS' },
    { name: 'Romania', code: 'RO' },
    { name: 'Bulgaria', code: 'BG' },
    { name: 'Serbia', code: 'SR' },
    { name: 'Montenegro', code: 'ME' },
    { name: 'Slovenia', code: 'SI' },
    { name: 'Slovakia', code: 'SK' },
    { name: 'Luxembourg', code: 'LU' },
    { name: 'Malta', code: 'MT' },
    { name: 'Cyprus', code: 'CY' },
    { name: 'Estonia', code: 'EE' },
    { name: 'Latvia', code: 'LV' },
    { name: 'Lithuania', code: 'LT' },
    { name: 'Russia', code: 'RU' },
    { name: 'Ukraine', code: 'UA' },
    { name: 'Georgia', code: 'GE' },
    { name: 'United States', code: 'US' },
    { name: 'Canada', code: 'CA' },
    { name: 'Mexico', code: 'MX' },
    { name: 'Brazil', code: 'BR' },
    { name: 'Argentina', code: 'AR' },
    { name: 'Chile', code: 'CL' },
    { name: 'Colombia', code: 'CO' },
    { name: 'Peru', code: 'PE' },
    { name: 'Costa Rica', code: 'CR' },
    { name: 'Panama', code: 'PA' },
    { name: 'Cuba', code: 'CU' },
    { name: 'Dominican Republic', code: 'DO' },
    { name: 'Jamaica', code: 'JM' },
    { name: 'Bahamas', code: 'BS' },
    { name: 'Ecuador', code: 'EC' },
    { name: 'Uruguay', code: 'UY' },
    { name: 'Bolivia', code: 'BO' },
    { name: 'Guatemala', code: 'GT' },
    { name: 'Honduras', code: 'HN' },
    { name: 'Belize', code: 'BZ' },
    { name: 'South Africa', code: 'ZA' },
    { name: 'Morocco', code: 'MA' },
    { name: 'Tunisia', code: 'TN' },
    { name: 'Kenya', code: 'KE' },
    { name: 'Tanzania', code: 'TZ' },
    { name: 'Nigeria', code: 'NG' },
    { name: 'Ghana', code: 'GH' },
    { name: 'Ethiopia', code: 'ET' },
    { name: 'Mauritius', code: 'MU' },
    { name: 'Seychelles', code: 'SC' },
    { name: 'Rwanda', code: 'RW' },
    { name: 'Namibia', code: 'NA' },
];

/**
 * Extract country code from a LiteAPI formattedAddress string.
 * The country is usually the last part after the last comma.
 * e.g., "Benguet, Philippines" → "PH", "South Korea" → "KR"
 *
 * If formattedAddress is empty (e.g., city-states like Singapore),
 * falls back to checking if displayName itself is a country name.
 */
export function extractCountryCode(formattedAddress: string, displayName?: string): string {
    if (formattedAddress) {
        // Get the last part (country name) after the last comma
        const parts = formattedAddress.split(',').map(s => s.trim());
        const countryName = parts[parts.length - 1].toLowerCase();
        const code = COUNTRY_NAME_TO_CODE[countryName];
        if (code) return code;
    }

    // Fallback: the displayName itself might be a country name
    // (e.g., "Singapore" has empty formattedAddress)
    if (displayName) {
        const code = COUNTRY_NAME_TO_CODE[displayName.toLowerCase()];
        if (code) return code;
    }

    return '';
}

/**
 * ISO country code → currency code mapping.
 * Maps the USER's country to their local currency for display.
 */
export const COUNTRY_TO_CURRENCY: Record<string, string> = {
    'PH': 'PHP',
    'KR': 'KRW',
    'JP': 'JPY',
    'US': 'USD',
    'GB': 'GBP',
    'AU': 'AUD',
    'CA': 'CAD',
    'SG': 'SGD',
    'MY': 'MYR',
    'TH': 'THB',
    'VN': 'VND',
    'ID': 'IDR',
    'IN': 'INR',
    'CN': 'CNY',
    'TW': 'TWD',
    'HK': 'HKD',
    'AE': 'AED',
    'SA': 'SAR',
    'QA': 'QAR',
    'EU': 'EUR', // Eurozone placeholder
    // Eurozone countries
    'FR': 'EUR',
    'DE': 'EUR',
    'IT': 'EUR',
    'ES': 'EUR',
    'PT': 'EUR',
    'NL': 'EUR',
    'BE': 'EUR',
    'AT': 'EUR',
    'IE': 'EUR',
    'FI': 'EUR',
    'GR': 'EUR',
    'SK': 'EUR',
    'SI': 'EUR',
    'LU': 'EUR',
    'MT': 'EUR',
    'CY': 'EUR',
    'EE': 'EUR',
    'LV': 'EUR',
    'LT': 'EUR',
    'HR': 'EUR',
    // Non-Euro Europe
    'CH': 'CHF',
    'SE': 'SEK',
    'NO': 'NOK',
    'DK': 'DKK',
    'CZ': 'CZK',
    'PL': 'PLN',
    'HU': 'HUF',
    'RO': 'RON',
    'BG': 'BGN',
    'IS': 'ISK',
    // Americas
    'MX': 'MXN',
    'BR': 'BRL',
    'AR': 'ARS',
    'CL': 'CLP',
    'CO': 'COP',
    'PE': 'PEN',
    // Africa
    'ZA': 'ZAR',
    'EG': 'EGP',
    'MA': 'MAD',
    'KE': 'KES',
    'NG': 'NGN',
    // Others
    'NZ': 'NZD',
    'TR': 'TRY',
    'RU': 'RUB',
    'IL': 'ILS',
};

/**
 * Get currency code for a given user country code.
 * Defaults to USD if the country is unknown.
 */
export function getCurrencyForCountry(countryCode: string): string {
    return COUNTRY_TO_CURRENCY[countryCode] || 'USD';
}
