/**
 * Airport → city + ISO 3166-1 alpha-2 country code lookup.
 *
 * Used to build hotel search URLs after a flight booking so the correct
 * countryCode is passed to hotel providers (LiteAPI, and future providers).
 *
 * When a code is missing, the airport code itself is used as the city name
 * and countryCode is omitted — which may cause hotel search errors on some
 * providers. Add missing airports here rather than patching call sites.
 *
 * Coverage: ~600 airports across all regions.
 */
export const AIRPORT_INFO: Record<string, { city: string; cc: string }> = {

    // ── Southeast Asia ────────────────────────────────────────────────────────
    // Thailand
    BKK: { city: 'Bangkok', cc: 'TH' },
    DMK: { city: 'Bangkok', cc: 'TH' },
    HKT: { city: 'Phuket', cc: 'TH' },
    CNX: { city: 'Chiang Mai', cc: 'TH' },
    CEI: { city: 'Chiang Rai', cc: 'TH' },
    USM: { city: 'Koh Samui', cc: 'TH' },
    KBV: { city: 'Krabi', cc: 'TH' },
    UTP: { city: 'Pattaya', cc: 'TH' },
    HDY: { city: 'Hat Yai', cc: 'TH' },
    UBP: { city: 'Ubon Ratchathani', cc: 'TH' },
    KKC: { city: 'Khon Kaen', cc: 'TH' },
    // Singapore
    SIN: { city: 'Singapore', cc: 'SG' },
    // Philippines
    MNL: { city: 'Manila', cc: 'PH' },
    CEB: { city: 'Cebu', cc: 'PH' },
    CRK: { city: 'Angeles', cc: 'PH' },
    ILO: { city: 'Iloilo', cc: 'PH' },
    DVO: { city: 'Davao', cc: 'PH' },
    PPS: { city: 'Puerto Princesa', cc: 'PH' },
    TAG: { city: 'Tagbilaran', cc: 'PH' },
    ZAM: { city: 'Zamboanga', cc: 'PH' },
    CGY: { city: 'Cagayan de Oro', cc: 'PH' },
    GES: { city: 'General Santos', cc: 'PH' },
    KLO: { city: 'Kalibo', cc: 'PH' },
    MPH: { city: 'Caticlan', cc: 'PH' },
    CYP: { city: 'Calbayog', cc: 'PH' },
    TAC: { city: 'Tacloban', cc: 'PH' },
    BCD: { city: 'Bacolod', cc: 'PH' },
    // Malaysia
    KUL: { city: 'Kuala Lumpur', cc: 'MY' },
    SZB: { city: 'Kuala Lumpur', cc: 'MY' },
    PEN: { city: 'Penang', cc: 'MY' },
    LGK: { city: 'Langkawi', cc: 'MY' },
    BKI: { city: 'Kota Kinabalu', cc: 'MY' },
    KCH: { city: 'Kuching', cc: 'MY' },
    JHB: { city: 'Johor Bahru', cc: 'MY' },
    MYY: { city: 'Miri', cc: 'MY' },
    SDK: { city: 'Sandakan', cc: 'MY' },
    TWU: { city: 'Tawau', cc: 'MY' },
    // Indonesia
    CGK: { city: 'Jakarta', cc: 'ID' },
    DPS: { city: 'Bali', cc: 'ID' },
    SUB: { city: 'Surabaya', cc: 'ID' },
    UPG: { city: 'Makassar', cc: 'ID' },
    MDC: { city: 'Manado', cc: 'ID' },
    BPN: { city: 'Balikpapan', cc: 'ID' },
    PLM: { city: 'Palembang', cc: 'ID' },
    MES: { city: 'Medan', cc: 'ID' },
    KNO: { city: 'Medan', cc: 'ID' },
    PKU: { city: 'Pekanbaru', cc: 'ID' },
    PNK: { city: 'Pontianak', cc: 'ID' },
    AMQ: { city: 'Ambon', cc: 'ID' },
    TIM: { city: 'Timika', cc: 'ID' },
    LOP: { city: 'Lombok', cc: 'ID' },
    YIA: { city: 'Yogyakarta', cc: 'ID' },
    JOG: { city: 'Yogyakarta', cc: 'ID' },
    SOC: { city: 'Solo', cc: 'ID' },
    SRG: { city: 'Semarang', cc: 'ID' },
    // Vietnam
    SGN: { city: 'Ho Chi Minh City', cc: 'VN' },
    HAN: { city: 'Hanoi', cc: 'VN' },
    DAD: { city: 'Da Nang', cc: 'VN' },
    CXR: { city: 'Nha Trang', cc: 'VN' },
    PQC: { city: 'Phu Quoc', cc: 'VN' },
    HPH: { city: 'Hai Phong', cc: 'VN' },
    HUI: { city: 'Hue', cc: 'VN' },
    VCA: { city: 'Can Tho', cc: 'VN' },
    VCS: { city: 'Con Dao', cc: 'VN' },
    // Cambodia
    PNH: { city: 'Phnom Penh', cc: 'KH' },
    REP: { city: 'Siem Reap', cc: 'KH' },
    KOS: { city: 'Sihanoukville', cc: 'KH' },
    // Myanmar
    RGN: { city: 'Yangon', cc: 'MM' },
    MDL: { city: 'Mandalay', cc: 'MM' },
    NYU: { city: 'Bagan', cc: 'MM' },
    // Laos
    VTE: { city: 'Vientiane', cc: 'LA' },
    LPQ: { city: 'Luang Prabang', cc: 'LA' },
    // Brunei
    BWN: { city: 'Bandar Seri Begawan', cc: 'BN' },
    // Timor-Leste
    DIL: { city: 'Dili', cc: 'TL' },

    // ── East Asia ─────────────────────────────────────────────────────────────
    // Japan
    NRT: { city: 'Tokyo', cc: 'JP' },
    HND: { city: 'Tokyo', cc: 'JP' },
    KIX: { city: 'Osaka', cc: 'JP' },
    ITM: { city: 'Osaka', cc: 'JP' },
    CTS: { city: 'Sapporo', cc: 'JP' },
    FUK: { city: 'Fukuoka', cc: 'JP' },
    NGO: { city: 'Nagoya', cc: 'JP' },
    OKA: { city: 'Okinawa', cc: 'JP' },
    HIJ: { city: 'Hiroshima', cc: 'JP' },
    KMQ: { city: 'Komatsu', cc: 'JP' },
    SDJ: { city: 'Sendai', cc: 'JP' },
    AOJ: { city: 'Aomori', cc: 'JP' },
    AXT: { city: 'Akita', cc: 'JP' },
    KOJ: { city: 'Kagoshima', cc: 'JP' },
    NGS: { city: 'Nagasaki', cc: 'JP' },
    KMJ: { city: 'Kumamoto', cc: 'JP' },
    OIT: { city: 'Oita', cc: 'JP' },
    MYJ: { city: 'Matsuyama', cc: 'JP' },
    TAK: { city: 'Takamatsu', cc: 'JP' },
    TKS: { city: 'Tokushima', cc: 'JP' },
    UKB: { city: 'Kobe', cc: 'JP' },
    // South Korea
    ICN: { city: 'Seoul', cc: 'KR' },
    GMP: { city: 'Seoul', cc: 'KR' },
    PUS: { city: 'Busan', cc: 'KR' },
    CJU: { city: 'Jeju', cc: 'KR' },
    TAE: { city: 'Daegu', cc: 'KR' },
    CJJ: { city: 'Cheongju', cc: 'KR' },
    KWJ: { city: 'Gwangju', cc: 'KR' },
    USN: { city: 'Ulsan', cc: 'KR' },
    WJU: { city: 'Wonju', cc: 'KR' },
    RSU: { city: 'Yeosu', cc: 'KR' },
    // China
    PEK: { city: 'Beijing', cc: 'CN' },
    PKX: { city: 'Beijing', cc: 'CN' },
    PVG: { city: 'Shanghai', cc: 'CN' },
    SHA: { city: 'Shanghai', cc: 'CN' },
    CAN: { city: 'Guangzhou', cc: 'CN' },
    SZX: { city: 'Shenzhen', cc: 'CN' },
    CTU: { city: 'Chengdu', cc: 'CN' },
    TFU: { city: 'Chengdu', cc: 'CN' },
    KMG: { city: 'Kunming', cc: 'CN' },
    XIY: { city: 'Xi\'an', cc: 'CN' },
    WUH: { city: 'Wuhan', cc: 'CN' },
    CSX: { city: 'Changsha', cc: 'CN' },
    HGH: { city: 'Hangzhou', cc: 'CN' },
    NKG: { city: 'Nanjing', cc: 'CN' },
    XMN: { city: 'Xiamen', cc: 'CN' },
    FOC: { city: 'Fuzhou', cc: 'CN' },
    HAK: { city: 'Haikou', cc: 'CN' },
    SYX: { city: 'Sanya', cc: 'CN' },
    CKG: { city: 'Chongqing', cc: 'CN' },
    HRB: { city: 'Harbin', cc: 'CN' },
    SHE: { city: 'Shenyang', cc: 'CN' },
    DLC: { city: 'Dalian', cc: 'CN' },
    TAO: { city: 'Qingdao', cc: 'CN' },
    TSN: { city: 'Tianjin', cc: 'CN' },
    CGO: { city: 'Zhengzhou', cc: 'CN' },
    TNA: { city: 'Jinan', cc: 'CN' },
    NNG: { city: 'Nanning', cc: 'CN' },
    KWE: { city: 'Guiyang', cc: 'CN' },
    URC: { city: 'Urumqi', cc: 'CN' },
    LHW: { city: 'Lanzhou', cc: 'CN' },
    XNN: { city: 'Xining', cc: 'CN' },
    INC: { city: 'Yinchuan', cc: 'CN' },
    HET: { city: 'Hohhot', cc: 'CN' },
    // Taiwan
    TPE: { city: 'Taipei', cc: 'TW' },
    TSA: { city: 'Taipei', cc: 'TW' },
    KHH: { city: 'Kaohsiung', cc: 'TW' },
    RMQ: { city: 'Taichung', cc: 'TW' },
    TNN: { city: 'Tainan', cc: 'TW' },
    // Hong Kong / Macau
    HKG: { city: 'Hong Kong', cc: 'HK' },
    MFM: { city: 'Macau', cc: 'MO' },
    // Mongolia
    ULN: { city: 'Ulaanbaatar', cc: 'MN' },

    // ── South Asia ────────────────────────────────────────────────────────────
    // India
    DEL: { city: 'New Delhi', cc: 'IN' },
    BOM: { city: 'Mumbai', cc: 'IN' },
    BLR: { city: 'Bengaluru', cc: 'IN' },
    MAA: { city: 'Chennai', cc: 'IN' },
    CCU: { city: 'Kolkata', cc: 'IN' },
    HYD: { city: 'Hyderabad', cc: 'IN' },
    COK: { city: 'Kochi', cc: 'IN' },
    AMD: { city: 'Ahmedabad', cc: 'IN' },
    PNQ: { city: 'Pune', cc: 'IN' },
    GOI: { city: 'Goa', cc: 'IN' },
    JAI: { city: 'Jaipur', cc: 'IN' },
    LKO: { city: 'Lucknow', cc: 'IN' },
    VNS: { city: 'Varanasi', cc: 'IN' },
    PAT: { city: 'Patna', cc: 'IN' },
    IXR: { city: 'Ranchi', cc: 'IN' },
    BBI: { city: 'Bhubaneswar', cc: 'IN' },
    GAU: { city: 'Guwahati', cc: 'IN' },
    IXB: { city: 'Bagdogra', cc: 'IN' },
    IXC: { city: 'Chandigarh', cc: 'IN' },
    ATQ: { city: 'Amritsar', cc: 'IN' },
    SXR: { city: 'Srinagar', cc: 'IN' },
    LEH: { city: 'Leh', cc: 'IN' },
    IXM: { city: 'Madurai', cc: 'IN' },
    TRV: { city: 'Thiruvananthapuram', cc: 'IN' },
    CJB: { city: 'Coimbatore', cc: 'IN' },
    VTZ: { city: 'Visakhapatnam', cc: 'IN' },
    NAG: { city: 'Nagpur', cc: 'IN' },
    // Sri Lanka
    CMB: { city: 'Colombo', cc: 'LK' },
    HRI: { city: 'Hambantota', cc: 'LK' },
    // Nepal
    KTM: { city: 'Kathmandu', cc: 'NP' },
    PKR: { city: 'Pokhara', cc: 'NP' },
    // Bangladesh
    DAC: { city: 'Dhaka', cc: 'BD' },
    CGP: { city: 'Chittagong', cc: 'BD' },
    // Pakistan
    KHI: { city: 'Karachi', cc: 'PK' },
    LHE: { city: 'Lahore', cc: 'PK' },
    ISB: { city: 'Islamabad', cc: 'PK' },
    PEW: { city: 'Peshawar', cc: 'PK' },
    // Maldives
    MLE: { city: 'Malé', cc: 'MV' },
    // Bhutan
    PBH: { city: 'Paro', cc: 'BT' },
    // Afghanistan
    KBL: { city: 'Kabul', cc: 'AF' },

    // ── Middle East ───────────────────────────────────────────────────────────
    DXB: { city: 'Dubai', cc: 'AE' },
    AUH: { city: 'Abu Dhabi', cc: 'AE' },
    SHJ: { city: 'Sharjah', cc: 'AE' },
    DOH: { city: 'Doha', cc: 'QA' },
    KWI: { city: 'Kuwait City', cc: 'KW' },
    BAH: { city: 'Manama', cc: 'BH' },
    MCT: { city: 'Muscat', cc: 'OM' },
    SLL: { city: 'Salalah', cc: 'OM' },
    RUH: { city: 'Riyadh', cc: 'SA' },
    JED: { city: 'Jeddah', cc: 'SA' },
    DMM: { city: 'Dammam', cc: 'SA' },
    MED: { city: 'Medina', cc: 'SA' },
    ABH: { city: 'Al Baha', cc: 'SA' },
    TIF: { city: 'Taif', cc: 'SA' },
    AMM: { city: 'Amman', cc: 'JO' },
    AQJ: { city: 'Aqaba', cc: 'JO' },
    BEY: { city: 'Beirut', cc: 'LB' },
    TLV: { city: 'Tel Aviv', cc: 'IL' },
    BGW: { city: 'Baghdad', cc: 'IQ' },
    BSR: { city: 'Basra', cc: 'IQ' },
    EBL: { city: 'Erbil', cc: 'IQ' },
    IKA: { city: 'Tehran', cc: 'IR' },
    THR: { city: 'Tehran', cc: 'IR' },
    MHD: { city: 'Mashhad', cc: 'IR' },
    IFN: { city: 'Isfahan', cc: 'IR' },
    SYZ: { city: 'Shiraz', cc: 'IR' },
    DAM: { city: 'Damascus', cc: 'SY' },
    SAH: { city: 'Sana\'a', cc: 'YE' },
    ADE: { city: 'Aden', cc: 'YE' },

    // ── Central Asia ──────────────────────────────────────────────────────────
    ALA: { city: 'Almaty', cc: 'KZ' },
    NQZ: { city: 'Astana', cc: 'KZ' },
    TAS: { city: 'Tashkent', cc: 'UZ' },
    FRU: { city: 'Bishkek', cc: 'KG' },
    DYU: { city: 'Dushanbe', cc: 'TJ' },
    ASB: { city: 'Ashgabat', cc: 'TM' },

    // ── Europe ────────────────────────────────────────────────────────────────
    // UK & Ireland
    LHR: { city: 'London', cc: 'GB' },
    LGW: { city: 'London', cc: 'GB' },
    STN: { city: 'London', cc: 'GB' },
    LTN: { city: 'London', cc: 'GB' },
    LCY: { city: 'London', cc: 'GB' },
    MAN: { city: 'Manchester', cc: 'GB' },
    BHX: { city: 'Birmingham', cc: 'GB' },
    EDI: { city: 'Edinburgh', cc: 'GB' },
    GLA: { city: 'Glasgow', cc: 'GB' },
    BRS: { city: 'Bristol', cc: 'GB' },
    NCL: { city: 'Newcastle', cc: 'GB' },
    LBA: { city: 'Leeds', cc: 'GB' },
    EMA: { city: 'Nottingham', cc: 'GB' },
    LPL: { city: 'Liverpool', cc: 'GB' },
    SOU: { city: 'Southampton', cc: 'GB' },
    ABZ: { city: 'Aberdeen', cc: 'GB' },
    INV: { city: 'Inverness', cc: 'GB' },
    BFS: { city: 'Belfast', cc: 'GB' },
    DUB: { city: 'Dublin', cc: 'IE' },
    ORK: { city: 'Cork', cc: 'IE' },
    SNN: { city: 'Shannon', cc: 'IE' },
    // France
    CDG: { city: 'Paris', cc: 'FR' },
    ORY: { city: 'Paris', cc: 'FR' },
    NCE: { city: 'Nice', cc: 'FR' },
    LYS: { city: 'Lyon', cc: 'FR' },
    MRS: { city: 'Marseille', cc: 'FR' },
    TLS: { city: 'Toulouse', cc: 'FR' },
    BOD: { city: 'Bordeaux', cc: 'FR' },
    NTE: { city: 'Nantes', cc: 'FR' },
    SXB: { city: 'Strasbourg', cc: 'FR' },
    LIL: { city: 'Lille', cc: 'FR' },
    // Germany
    FRA: { city: 'Frankfurt', cc: 'DE' },
    MUC: { city: 'Munich', cc: 'DE' },
    BER: { city: 'Berlin', cc: 'DE' },
    DUS: { city: 'Düsseldorf', cc: 'DE' },
    HAM: { city: 'Hamburg', cc: 'DE' },
    CGN: { city: 'Cologne', cc: 'DE' },
    STR: { city: 'Stuttgart', cc: 'DE' },
    NUE: { city: 'Nuremberg', cc: 'DE' },
    HAJ: { city: 'Hannover', cc: 'DE' },
    BRE: { city: 'Bremen', cc: 'DE' },
    LEJ: { city: 'Leipzig', cc: 'DE' },
    DRS: { city: 'Dresden', cc: 'DE' },
    // Netherlands
    AMS: { city: 'Amsterdam', cc: 'NL' },
    EIN: { city: 'Eindhoven', cc: 'NL' },
    RTM: { city: 'Rotterdam', cc: 'NL' },
    // Spain
    MAD: { city: 'Madrid', cc: 'ES' },
    BCN: { city: 'Barcelona', cc: 'ES' },
    AGP: { city: 'Málaga', cc: 'ES' },
    ALC: { city: 'Alicante', cc: 'ES' },
    VLC: { city: 'Valencia', cc: 'ES' },
    SVQ: { city: 'Seville', cc: 'ES' },
    BIO: { city: 'Bilbao', cc: 'ES' },
    PMI: { city: 'Palma de Mallorca', cc: 'ES' },
    IBZ: { city: 'Ibiza', cc: 'ES' },
    TFS: { city: 'Tenerife', cc: 'ES' },
    LPA: { city: 'Gran Canaria', cc: 'ES' },
    ACE: { city: 'Lanzarote', cc: 'ES' },
    FUE: { city: 'Fuerteventura', cc: 'ES' },
    SDR: { city: 'Santander', cc: 'ES' },
    // Italy
    FCO: { city: 'Rome', cc: 'IT' },
    CIA: { city: 'Rome', cc: 'IT' },
    MXP: { city: 'Milan', cc: 'IT' },
    LIN: { city: 'Milan', cc: 'IT' },
    BGY: { city: 'Milan', cc: 'IT' },
    VCE: { city: 'Venice', cc: 'IT' },
    FLR: { city: 'Florence', cc: 'IT' },
    NAP: { city: 'Naples', cc: 'IT' },
    CTA: { city: 'Catania', cc: 'IT' },
    PMO: { city: 'Palermo', cc: 'IT' },
    BRI: { city: 'Bari', cc: 'IT' },
    PSA: { city: 'Pisa', cc: 'IT' },
    BOL: { city: 'Bologna', cc: 'IT' },
    TRN: { city: 'Turin', cc: 'IT' },
    GOA: { city: 'Genoa', cc: 'IT' },
    // Portugal
    LIS: { city: 'Lisbon', cc: 'PT' },
    OPO: { city: 'Porto', cc: 'PT' },
    FAO: { city: 'Faro', cc: 'PT' },
    FNC: { city: 'Madeira', cc: 'PT' },
    PDL: { city: 'Ponta Delgada', cc: 'PT' },
    // Switzerland
    ZRH: { city: 'Zurich', cc: 'CH' },
    GVA: { city: 'Geneva', cc: 'CH' },
    BSL: { city: 'Basel', cc: 'CH' },
    BRN: { city: 'Bern', cc: 'CH' },
    // Austria
    VIE: { city: 'Vienna', cc: 'AT' },
    GRZ: { city: 'Graz', cc: 'AT' },
    INN: { city: 'Innsbruck', cc: 'AT' },
    SZG: { city: 'Salzburg', cc: 'AT' },
    // Belgium
    BRU: { city: 'Brussels', cc: 'BE' },
    CRL: { city: 'Brussels', cc: 'BE' },
    ANR: { city: 'Antwerp', cc: 'BE' },
    // Scandinavia
    ARN: { city: 'Stockholm', cc: 'SE' },
    NYO: { city: 'Stockholm', cc: 'SE' },
    GOT: { city: 'Gothenburg', cc: 'SE' },
    MMX: { city: 'Malmö', cc: 'SE' },
    OSL: { city: 'Oslo', cc: 'NO' },
    TRF: { city: 'Oslo', cc: 'NO' },
    BGO: { city: 'Bergen', cc: 'NO' },
    TRD: { city: 'Trondheim', cc: 'NO' },
    TOS: { city: 'Tromsø', cc: 'NO' },
    CPH: { city: 'Copenhagen', cc: 'DK' },
    BLL: { city: 'Billund', cc: 'DK' },
    AAL: { city: 'Aalborg', cc: 'DK' },
    HEL: { city: 'Helsinki', cc: 'FI' },
    TMP: { city: 'Tampere', cc: 'FI' },
    OUL: { city: 'Oulu', cc: 'FI' },
    RVN: { city: 'Rovaniemi', cc: 'FI' },
    // Poland
    WAW: { city: 'Warsaw', cc: 'PL' },
    WMI: { city: 'Warsaw', cc: 'PL' },
    KRK: { city: 'Kraków', cc: 'PL' },
    GDN: { city: 'Gdańsk', cc: 'PL' },
    POZ: { city: 'Poznań', cc: 'PL' },
    WRO: { city: 'Wrocław', cc: 'PL' },
    KTW: { city: 'Katowice', cc: 'PL' },
    // Czech Republic & Slovakia
    PRG: { city: 'Prague', cc: 'CZ' },
    BRQ: { city: 'Brno', cc: 'CZ' },
    BTS: { city: 'Bratislava', cc: 'SK' },
    KSC: { city: 'Košice', cc: 'SK' },
    // Hungary
    BUD: { city: 'Budapest', cc: 'HU' },
    // Romania
    OTP: { city: 'Bucharest', cc: 'RO' },
    CLJ: { city: 'Cluj-Napoca', cc: 'RO' },
    TSR: { city: 'Timișoara', cc: 'RO' },
    // Bulgaria
    SOF: { city: 'Sofia', cc: 'BG' },
    VAR: { city: 'Varna', cc: 'BG' },
    BOJ: { city: 'Burgas', cc: 'BG' },
    // Croatia
    ZAG: { city: 'Zagreb', cc: 'HR' },
    SPU: { city: 'Split', cc: 'HR' },
    DBV: { city: 'Dubrovnik', cc: 'HR' },
    ZAD: { city: 'Zadar', cc: 'HR' },
    // Greece
    ATH: { city: 'Athens', cc: 'GR' },
    SKG: { city: 'Thessaloniki', cc: 'GR' },
    HER: { city: 'Heraklion', cc: 'GR' },
    RHO: { city: 'Rhodes', cc: 'GR' },
    CFU: { city: 'Corfu', cc: 'GR' },
    JMK: { city: 'Mykonos', cc: 'GR' },
    JTR: { city: 'Santorini', cc: 'GR' },
    ZTH: { city: 'Zakynthos', cc: 'GR' },
    KGS: { city: 'Kos', cc: 'GR' },
    // Turkey
    IST: { city: 'Istanbul', cc: 'TR' },
    SAW: { city: 'Istanbul', cc: 'TR' },
    AYT: { city: 'Antalya', cc: 'TR' },
    ADB: { city: 'Izmir', cc: 'TR' },
    ESB: { city: 'Ankara', cc: 'TR' },
    BJV: { city: 'Bodrum', cc: 'TR' },
    DLM: { city: 'Dalaman', cc: 'TR' },
    TZX: { city: 'Trabzon', cc: 'TR' },
    GZP: { city: 'Alanya', cc: 'TR' },
    // Ukraine & Moldova
    KBP: { city: 'Kyiv', cc: 'UA' },
    IEV: { city: 'Kyiv', cc: 'UA' },
    ODS: { city: 'Odessa', cc: 'UA' },
    LWO: { city: 'Lviv', cc: 'UA' },
    KHK: { city: 'Kharkiv', cc: 'UA' },
    KIV: { city: 'Chișinău', cc: 'MD' },
    // Russia
    SVO: { city: 'Moscow', cc: 'RU' },
    DME: { city: 'Moscow', cc: 'RU' },
    VKO: { city: 'Moscow', cc: 'RU' },
    LED: { city: 'Saint Petersburg', cc: 'RU' },
    OVB: { city: 'Novosibirsk', cc: 'RU' },
    SVX: { city: 'Yekaterinburg', cc: 'RU' },
    KZN: { city: 'Kazan', cc: 'RU' },
    ROV: { city: 'Rostov-on-Don', cc: 'RU' },
    KRR: { city: 'Krasnodar', cc: 'RU' },
    // Baltic States
    RIX: { city: 'Riga', cc: 'LV' },
    TLL: { city: 'Tallinn', cc: 'EE' },
    VNO: { city: 'Vilnius', cc: 'LT' },
    // Serbia, Slovenia, North Macedonia
    BEG: { city: 'Belgrade', cc: 'RS' },
    LJU: { city: 'Ljubljana', cc: 'SI' },
    SKP: { city: 'Skopje', cc: 'MK' },
    // Bosnia, Albania, Kosovo, Montenegro
    SJJ: { city: 'Sarajevo', cc: 'BA' },
    TIA: { city: 'Tirana', cc: 'AL' },
    PRN: { city: 'Pristina', cc: 'XK' },
    TGD: { city: 'Podgorica', cc: 'ME' },
    // Iceland
    KEF: { city: 'Reykjavik', cc: 'IS' },
    // Malta & Cyprus
    MLA: { city: 'Malta', cc: 'MT' },
    LCA: { city: 'Larnaca', cc: 'CY' },
    PFO: { city: 'Paphos', cc: 'CY' },
    // Luxembourg
    LUX: { city: 'Luxembourg', cc: 'LU' },

    // ── Africa ────────────────────────────────────────────────────────────────
    // North Africa
    CAI: { city: 'Cairo', cc: 'EG' },
    HRG: { city: 'Hurghada', cc: 'EG' },
    SSH: { city: 'Sharm El Sheikh', cc: 'EG' },
    LXR: { city: 'Luxor', cc: 'EG' },
    CMN: { city: 'Casablanca', cc: 'MA' },
    RAK: { city: 'Marrakech', cc: 'MA' },
    FEZ: { city: 'Fez', cc: 'MA' },
    AGA: { city: 'Agadir', cc: 'MA' },
    TNG: { city: 'Tangier', cc: 'MA' },
    ALG: { city: 'Algiers', cc: 'DZ' },
    TUN: { city: 'Tunis', cc: 'TN' },
    DJE: { city: 'Djerba', cc: 'TN' },
    TIP: { city: 'Tripoli', cc: 'LY' },
    // East Africa
    NBO: { city: 'Nairobi', cc: 'KE' },
    MBA: { city: 'Mombasa', cc: 'KE' },
    EBB: { city: 'Entebbe', cc: 'UG' },
    DAR: { city: 'Dar es Salaam', cc: 'TZ' },
    JRO: { city: 'Kilimanjaro', cc: 'TZ' },
    ZNZ: { city: 'Zanzibar', cc: 'TZ' },
    ADD: { city: 'Addis Ababa', cc: 'ET' },
    KGL: { city: 'Kigali', cc: 'RW' },
    DJI: { city: 'Djibouti', cc: 'DJ' },
    // West Africa
    LOS: { city: 'Lagos', cc: 'NG' },
    ABV: { city: 'Abuja', cc: 'NG' },
    KAN: { city: 'Kano', cc: 'NG' },
    ACC: { city: 'Accra', cc: 'GH' },
    ABJ: { city: 'Abidjan', cc: 'CI' },
    DKR: { city: 'Dakar', cc: 'SN' },
    COO: { city: 'Cotonou', cc: 'BJ' },
    // Southern Africa
    JNB: { city: 'Johannesburg', cc: 'ZA' },
    CPT: { city: 'Cape Town', cc: 'ZA' },
    DUR: { city: 'Durban', cc: 'ZA' },
    HRE: { city: 'Harare', cc: 'ZW' },
    LUN: { city: 'Lusaka', cc: 'ZM' },
    MQP: { city: 'Kruger', cc: 'ZA' },
    GBE: { city: 'Gaborone', cc: 'BW' },
    WDH: { city: 'Windhoek', cc: 'NA' },
    TNR: { city: 'Antananarivo', cc: 'MG' },
    MRU: { city: 'Mauritius', cc: 'MU' },
    RUN: { city: 'Réunion', cc: 'RE' },
    SEZ: { city: 'Seychelles', cc: 'SC' },

    // ── Oceania ───────────────────────────────────────────────────────────────
    // Australia
    SYD: { city: 'Sydney', cc: 'AU' },
    MEL: { city: 'Melbourne', cc: 'AU' },
    BNE: { city: 'Brisbane', cc: 'AU' },
    PER: { city: 'Perth', cc: 'AU' },
    ADL: { city: 'Adelaide', cc: 'AU' },
    OOL: { city: 'Gold Coast', cc: 'AU' },
    CBR: { city: 'Canberra', cc: 'AU' },
    HBA: { city: 'Hobart', cc: 'AU' },
    DRW: { city: 'Darwin', cc: 'AU' },
    TSV: { city: 'Townsville', cc: 'AU' },
    CNS: { city: 'Cairns', cc: 'AU' },
    // New Zealand
    AKL: { city: 'Auckland', cc: 'NZ' },
    WLG: { city: 'Wellington', cc: 'NZ' },
    CHC: { city: 'Christchurch', cc: 'NZ' },
    ZQN: { city: 'Queenstown', cc: 'NZ' },
    DUD: { city: 'Dunedin', cc: 'NZ' },
    // Pacific Islands
    NAN: { city: 'Nadi', cc: 'FJ' },
    SUV: { city: 'Suva', cc: 'FJ' },
    PPT: { city: 'Papeete', cc: 'PF' },
    APW: { city: 'Apia', cc: 'WS' },
    INU: { city: 'Nauru', cc: 'NR' },
    TBU: { city: 'Nukualofa', cc: 'TO' },
    VLI: { city: 'Port Vila', cc: 'VU' },
    HIR: { city: 'Honiara', cc: 'SB' },
    POM: { city: 'Port Moresby', cc: 'PG' },
    GUM: { city: 'Guam', cc: 'GU' },
    SPN: { city: 'Saipan', cc: 'MP' },

    // ── North America ─────────────────────────────────────────────────────────
    // USA — East
    JFK: { city: 'New York', cc: 'US' },
    LGA: { city: 'New York', cc: 'US' },
    EWR: { city: 'Newark', cc: 'US' },
    BOS: { city: 'Boston', cc: 'US' },
    PHL: { city: 'Philadelphia', cc: 'US' },
    IAD: { city: 'Washington DC', cc: 'US' },
    DCA: { city: 'Washington DC', cc: 'US' },
    BWI: { city: 'Baltimore', cc: 'US' },
    MIA: { city: 'Miami', cc: 'US' },
    FLL: { city: 'Fort Lauderdale', cc: 'US' },
    TPA: { city: 'Tampa', cc: 'US' },
    MCO: { city: 'Orlando', cc: 'US' },
    JAX: { city: 'Jacksonville', cc: 'US' },
    ATL: { city: 'Atlanta', cc: 'US' },
    CLT: { city: 'Charlotte', cc: 'US' },
    RDU: { city: 'Raleigh', cc: 'US' },
    DFW: { city: 'Dallas', cc: 'US' },
    DAL: { city: 'Dallas', cc: 'US' },
    IAH: { city: 'Houston', cc: 'US' },
    HOU: { city: 'Houston', cc: 'US' },
    MSY: { city: 'New Orleans', cc: 'US' },
    MEM: { city: 'Memphis', cc: 'US' },
    BNA: { city: 'Nashville', cc: 'US' },
    CVG: { city: 'Cincinnati', cc: 'US' },
    CMH: { city: 'Columbus', cc: 'US' },
    CLE: { city: 'Cleveland', cc: 'US' },
    PIT: { city: 'Pittsburgh', cc: 'US' },
    // USA — Midwest
    ORD: { city: 'Chicago', cc: 'US' },
    MDW: { city: 'Chicago', cc: 'US' },
    DTW: { city: 'Detroit', cc: 'US' },
    MSP: { city: 'Minneapolis', cc: 'US' },
    STL: { city: 'St. Louis', cc: 'US' },
    MKE: { city: 'Milwaukee', cc: 'US' },
    IND: { city: 'Indianapolis', cc: 'US' },
    OMA: { city: 'Omaha', cc: 'US' },
    MCI: { city: 'Kansas City', cc: 'US' },
    // USA — West
    LAX: { city: 'Los Angeles', cc: 'US' },
    SFO: { city: 'San Francisco', cc: 'US' },
    SJC: { city: 'San Jose', cc: 'US' },
    OAK: { city: 'Oakland', cc: 'US' },
    SEA: { city: 'Seattle', cc: 'US' },
    PDX: { city: 'Portland', cc: 'US' },
    LAS: { city: 'Las Vegas', cc: 'US' },
    PHX: { city: 'Phoenix', cc: 'US' },
    SAN: { city: 'San Diego', cc: 'US' },
    DEN: { city: 'Denver', cc: 'US' },
    SLC: { city: 'Salt Lake City', cc: 'US' },
    ABQ: { city: 'Albuquerque', cc: 'US' },
    TUS: { city: 'Tucson', cc: 'US' },
    BUR: { city: 'Burbank', cc: 'US' },
    ONT: { city: 'Ontario', cc: 'US' },
    SNA: { city: 'Orange County', cc: 'US' },
    SMF: { city: 'Sacramento', cc: 'US' },
    // USA — Alaska & Hawaii
    ANC: { city: 'Anchorage', cc: 'US' },
    FAI: { city: 'Fairbanks', cc: 'US' },
    HNL: { city: 'Honolulu', cc: 'US' },
    OGG: { city: 'Maui', cc: 'US' },
    KOA: { city: 'Kona', cc: 'US' },
    LIH: { city: 'Lihue', cc: 'US' },
    // Canada
    YYZ: { city: 'Toronto', cc: 'CA' },
    YYC: { city: 'Calgary', cc: 'CA' },
    YVR: { city: 'Vancouver', cc: 'CA' },
    YUL: { city: 'Montreal', cc: 'CA' },
    YOW: { city: 'Ottawa', cc: 'CA' },
    YEG: { city: 'Edmonton', cc: 'CA' },
    YWG: { city: 'Winnipeg', cc: 'CA' },
    YHZ: { city: 'Halifax', cc: 'CA' },
    YQB: { city: 'Quebec City', cc: 'CA' },
    YXE: { city: 'Saskatoon', cc: 'CA' },
    YQR: { city: 'Regina', cc: 'CA' },
    YZF: { city: 'Yellowknife', cc: 'CA' },
    // Mexico
    MEX: { city: 'Mexico City', cc: 'MX' },
    CUN: { city: 'Cancún', cc: 'MX' },
    GDL: { city: 'Guadalajara', cc: 'MX' },
    MTY: { city: 'Monterrey', cc: 'MX' },
    SJD: { city: 'Los Cabos', cc: 'MX' },
    PVR: { city: 'Puerto Vallarta', cc: 'MX' },
    HMO: { city: 'Hermosillo', cc: 'MX' },
    TIJ: { city: 'Tijuana', cc: 'MX' },
    MID: { city: 'Mérida', cc: 'MX' },
    OAX: { city: 'Oaxaca', cc: 'MX' },
    ZIH: { city: 'Ixtapa', cc: 'MX' },
    ACA: { city: 'Acapulco', cc: 'MX' },
    // Caribbean
    HAV: { city: 'Havana', cc: 'CU' },
    VRA: { city: 'Varadero', cc: 'CU' },
    SDQ: { city: 'Santo Domingo', cc: 'DO' },
    PUJ: { city: 'Punta Cana', cc: 'DO' },
    SJU: { city: 'San Juan', cc: 'PR' },
    KIN: { city: 'Kingston', cc: 'JM' },
    MBJ: { city: 'Montego Bay', cc: 'JM' },
    NAS: { city: 'Nassau', cc: 'BS' },
    POS: { city: 'Port of Spain', cc: 'TT' },
    BGI: { city: 'Bridgetown', cc: 'BB' },
    ANU: { city: 'Antigua', cc: 'AG' },
    SXM: { city: 'Sint Maarten', cc: 'SX' },
    // Central America
    GUA: { city: 'Guatemala City', cc: 'GT' },
    SAL: { city: 'San Salvador', cc: 'SV' },
    TGU: { city: 'Tegucigalpa', cc: 'HN' },
    MGA: { city: 'Managua', cc: 'NI' },
    SJO: { city: 'San José', cc: 'CR' },
    PTY: { city: 'Panama City', cc: 'PA' },
    BZE: { city: 'Belize City', cc: 'BZ' },

    // ── South America ─────────────────────────────────────────────────────────
    GRU: { city: 'São Paulo', cc: 'BR' },
    CGH: { city: 'São Paulo', cc: 'BR' },
    VCP: { city: 'Campinas', cc: 'BR' },
    GIG: { city: 'Rio de Janeiro', cc: 'BR' },
    SDU: { city: 'Rio de Janeiro', cc: 'BR' },
    BSB: { city: 'Brasília', cc: 'BR' },
    SSA: { city: 'Salvador', cc: 'BR' },
    REC: { city: 'Recife', cc: 'BR' },
    FOR: { city: 'Fortaleza', cc: 'BR' },
    BEL: { city: 'Belém', cc: 'BR' },
    MAO: { city: 'Manaus', cc: 'BR' },
    CWB: { city: 'Curitiba', cc: 'BR' },
    POA: { city: 'Porto Alegre', cc: 'BR' },
    FLN: { city: 'Florianópolis', cc: 'BR' },
    EZE: { city: 'Buenos Aires', cc: 'AR' },
    AEP: { city: 'Buenos Aires', cc: 'AR' },
    COR: { city: 'Córdoba', cc: 'AR' },
    MDZ: { city: 'Mendoza', cc: 'AR' },
    BRC: { city: 'Bariloche', cc: 'AR' },
    USH: { city: 'Ushuaia', cc: 'AR' },
    SCL: { city: 'Santiago', cc: 'CL' },
    PMC: { city: 'Puerto Montt', cc: 'CL' },
    IQQ: { city: 'Iquique', cc: 'CL' },
    BOG: { city: 'Bogotá', cc: 'CO' },
    MDE: { city: 'Medellín', cc: 'CO' },
    CLO: { city: 'Cali', cc: 'CO' },
    CTG: { city: 'Cartagena', cc: 'CO' },
    LIM: { city: 'Lima', cc: 'PE' },
    CUZ: { city: 'Cusco', cc: 'PE' },
    AQP: { city: 'Arequipa', cc: 'PE' },
    UIO: { city: 'Quito', cc: 'EC' },
    GYE: { city: 'Guayaquil', cc: 'EC' },
    GPS: { city: 'Galápagos', cc: 'EC' },
    LPB: { city: 'La Paz', cc: 'BO' },
    VVI: { city: 'Santa Cruz', cc: 'BO' },
    ASU: { city: 'Asunción', cc: 'PY' },
    MVD: { city: 'Montevideo', cc: 'UY' },
    CCS: { city: 'Caracas', cc: 'VE' },
    PMV: { city: 'Margarita Island', cc: 'VE' },
    GEO: { city: 'Georgetown', cc: 'GY' },
    PBM: { city: 'Paramaribo', cc: 'SR' },
    CAY: { city: 'Cayenne', cc: 'GF' },
};

/**
 * Looks up city name and country code for an airport IATA code.
 * Falls back to the code itself as city name with empty country code.
 */
export function getAirportInfo(iataCode: string): { city: string; cc: string } {
    return AIRPORT_INFO[iataCode] ?? { city: iataCode, cc: '' };
}
